// Merchant name to domain mapping for logo lookups
// This maps common merchant names (normalized) to their website domains

export const MERCHANT_DOMAINS: Record<string, string> = {
  // Fast Food & Restaurants
  'mcdonalds': 'mcdonalds.com',
  'mcdonald': 'mcdonalds.com',
  'starbucks': 'starbucks.com',
  'chipotle': 'chipotle.com',
  'wendys': 'wendys.com',
  'wendy': 'wendys.com',
  'burgerking': 'bk.com',
  'burger king': 'bk.com',
  'tacobell': 'tacobell.com',
  'taco bell': 'tacobell.com',
  'chickfila': 'chick-fil-a.com',
  'chick-fil-a': 'chick-fil-a.com',
  'chickfilat': 'chick-fil-a.com',
  'kfc': 'kfc.com',
  'popeyes': 'popeyes.com',
  'dominos': 'dominos.com',
  'pizzahut': 'pizzahut.com',
  'pizza hut': 'pizzahut.com',
  'papajohns': 'papajohns.com',
  'papa johns': 'papajohns.com',
  'littlecaesars': 'littlecaesars.com',
  'subway': 'subway.com',
  'dunkin': 'dunkindonuts.com',
  'dunkindonuts': 'dunkindonuts.com',
  'panera': 'panerabread.com',
  'panerabread': 'panerabread.com',
  'applebees': 'applebees.com',
  'chilis': 'chilis.com',
  'olivegarden': 'olivegarden.com',
  'olive garden': 'olivegarden.com',
  'redlobster': 'redlobster.com',
  'red lobster': 'redlobster.com',
  'outback': 'outback.com',
  'outbacksteakhouse': 'outback.com',
  'buffalowildwings': 'buffalowildwings.com',
  'ihop': 'ihop.com',
  'dennys': 'dennys.com',
  'crackerbarrel': 'crackerbarrel.com',
  'cracker barrel': 'crackerbarrel.com',
  'fiveguys': 'fiveguys.com',
  'five guys': 'fiveguys.com',
  'sonic': 'sonicdrivein.com',
  'jackinthebox': 'jackinthebox.com',
  'jack in the box': 'jackinthebox.com',
  'arbys': 'arbys.com',
  'whataburger': 'whataburger.com',
  'innout': 'in-n-out.com',
  'in-n-out': 'in-n-out.com',
  'shakeshack': 'shakeshack.com',
  'shake shack': 'shakeshack.com',
  'wingstop': 'wingstop.com',
  'jerseysmikes': 'jerseymikes.com',
  'jersey mikes': 'jerseymikes.com',
  'jimmyjohns': 'jimmyjohns.com',
  'jimmy johns': 'jimmyjohns.com',
  'qdoba': 'qdoba.com',
  'moessouthwestgrill': 'moes.com',
  'moes': 'moes.com',
  'panda': 'pandaexpress.com',
  'pandaexpress': 'pandaexpress.com',
  'panda express': 'pandaexpress.com',
  'noodles': 'noodles.com',
  'noodlesandcompany': 'noodles.com',
  'zaxbys': 'zaxbys.com',
  'raisingcanes': 'raisingcanes.com',
  'raising canes': 'raisingcanes.com',
  'culvers': 'culvers.com',
  'cookout': 'cookout.com',

  // Coffee
  'peets': 'peets.com',
  'peetscoffee': 'peets.com',
  'caribou': 'cariboucoffee.com',
  'cariboucoffee': 'cariboucoffee.com',
  'dutchbros': 'dutchbros.com',
  'dutch bros': 'dutchbros.com',
  'timhortons': 'timhortons.com',
  'tim hortons': 'timhortons.com',

  // Retail & Department Stores
  'walmart': 'walmart.com',
  'target': 'target.com',
  'costco': 'costco.com',
  'sams': 'samsclub.com',
  'samsclub': 'samsclub.com',
  'amazon': 'amazon.com',
  'amzn': 'amazon.com',
  'wholefoodsmarket': 'wholefoodsmarket.com',
  'whole foods': 'wholefoodsmarket.com',
  'wholefoods': 'wholefoodsmarket.com',
  'bestbuy': 'bestbuy.com',
  'best buy': 'bestbuy.com',
  'homedepot': 'homedepot.com',
  'home depot': 'homedepot.com',
  'lowes': 'lowes.com',
  'menards': 'menards.com',
  'ikea': 'ikea.com',
  'bedbathandbeyond': 'bedbathandbeyond.com',
  'macys': 'macys.com',
  'nordstrom': 'nordstrom.com',
  'kohls': 'kohls.com',
  'jcpenney': 'jcpenney.com',
  'dillards': 'dillards.com',
  'marshalls': 'marshalls.com',
  'tjmaxx': 'tjmaxx.com',
  'ross': 'rossstores.com',
  'burlington': 'burlington.com',
  'oldnavy': 'oldnavy.com',
  'old navy': 'oldnavy.com',
  'gap': 'gap.com',
  'banana republic': 'bananarepublic.com',
  'bananarepublic': 'bananarepublic.com',
  'express': 'express.com',
  'forever21': 'forever21.com',
  'forever 21': 'forever21.com',
  'hm': 'hm.com',
  'h&m': 'hm.com',
  'zara': 'zara.com',
  'uniqlo': 'uniqlo.com',
  'nike': 'nike.com',
  'adidas': 'adidas.com',
  'underarmour': 'underarmour.com',
  'under armour': 'underarmour.com',
  'footlocker': 'footlocker.com',
  'finishline': 'finishline.com',
  'dickssportinggoods': 'dickssportinggoods.com',
  'dicks sporting goods': 'dickssportinggoods.com',
  'academy': 'academy.com',
  'rei': 'rei.com',
  'bathandbodyworks': 'bathandbodyworks.com',
  'bath and body works': 'bathandbodyworks.com',
  'victoriassecret': 'victoriassecret.com',
  'victorias secret': 'victoriassecret.com',
  'sephora': 'sephora.com',
  'ulta': 'ulta.com',
  'gamestop': 'gamestop.com',
  'barnesandnoble': 'barnesandnoble.com',
  'barnes and noble': 'barnesandnoble.com',
  'petco': 'petco.com',
  'petsmart': 'petsmart.com',
  'chewy': 'chewy.com',
  'staples': 'staples.com',
  'officemax': 'officedepot.com',
  'officedepot': 'officedepot.com',
  'michaels': 'michaels.com',
  'hobbylobby': 'hobbylobby.com',
  'hobby lobby': 'hobbylobby.com',
  'joann': 'joann.com',
  'dollar general': 'dollargeneral.com',
  'dollargeneral': 'dollargeneral.com',
  'dollartree': 'dollartree.com',
  'familydollar': 'familydollar.com',

  // Grocery Stores
  'kroger': 'kroger.com',
  'safeway': 'safeway.com',
  'albertsons': 'albertsons.com',
  'publix': 'publix.com',
  'wegmans': 'wegmans.com',
  'traderjoes': 'traderjoes.com',
  'trader joes': 'traderjoes.com',
  'aldi': 'aldi.us',
  'lidl': 'lidl.com',
  'heb': 'heb.com',
  'meijer': 'meijer.com',
  'winco': 'wincofoods.com',
  'sprouts': 'sprouts.com',
  'freshmarket': 'thefreshmarket.com',
  'harristeeter': 'harristeeter.com',
  'harris teeter': 'harristeeter.com',
  'giantfood': 'giantfood.com',
  'stopandshop': 'stopandshop.com',
  'foodlion': 'foodlion.com',
  'food lion': 'foodlion.com',
  'pigglywiggly': 'pigglywiggly.com',
  'winn-dixie': 'winndixie.com',
  'winndixie': 'winndixie.com',
  'shoprite': 'shoprite.com',
  'acme': 'acmemarkets.com',

  // Gas Stations
  'shell': 'shell.com',
  'exxon': 'exxon.com',
  'exxonmobil': 'exxon.com',
  'mobil': 'exxon.com',
  'chevron': 'chevron.com',
  'bp': 'bp.com',
  'sunoco': 'sunoco.com',
  'marathon': 'marathonpetroleum.com',
  'speedway': 'speedway.com',
  'circle k': 'circlek.com',
  'circlek': 'circlek.com',
  '7-eleven': '7-eleven.com',
  '7eleven': '7-eleven.com',
  'wawa': 'wawa.com',
  'sheetz': 'sheetz.com',
  'quiktrip': 'quiktrip.com',
  'qt': 'quiktrip.com',
  'racetrac': 'racetrac.com',
  'maverick': 'maverik.com',
  'caseys': 'caseys.com',
  'kwiktrip': 'kwiktrip.com',
  'kwik trip': 'kwiktrip.com',
  'cumberland': 'cumberlandfarms.com',
  'cumberlandfarms': 'cumberlandfarms.com',
  'thorntons': 'mythorntons.com',
  'getgo': 'getgo.com',
  'loves': 'loves.com',
  'pilot': 'pilotflyingj.com',
  'flyingj': 'pilotflyingj.com',
  'buccees': 'buc-ees.com',
  'buc-ees': 'buc-ees.com',

  // Pharmacies & Health
  'cvs': 'cvs.com',
  'walgreens': 'walgreens.com',
  'riteaid': 'riteaid.com',
  'rite aid': 'riteaid.com',
  'gnc': 'gnc.com',
  'vitaminshoppe': 'vitaminshoppe.com',

  // Tech & Electronics
  'apple': 'apple.com',
  'microsoft': 'microsoft.com',
  'google': 'google.com',
  'samsung': 'samsung.com',
  'dell': 'dell.com',
  'hp': 'hp.com',
  'lenovo': 'lenovo.com',
  'asus': 'asus.com',
  'newegg': 'newegg.com',
  'bh': 'bhphotovideo.com',
  'bhphoto': 'bhphotovideo.com',

  // Streaming & Entertainment
  'netflix': 'netflix.com',
  'hulu': 'hulu.com',
  'disney': 'disneyplus.com',
  'disneyplus': 'disneyplus.com',
  'disney+': 'disneyplus.com',
  'hbomax': 'max.com',
  'hbo': 'max.com',
  'max': 'max.com',
  'amazonprime': 'amazon.com',
  'primevideo': 'amazon.com',
  'spotify': 'spotify.com',
  'applemusic': 'apple.com',
  'pandora': 'pandora.com',
  'youtube': 'youtube.com',
  'youtubepremium': 'youtube.com',
  'youtubetv': 'youtube.com',
  'peacock': 'peacocktv.com',
  'paramount': 'paramountplus.com',
  'paramount+': 'paramountplus.com',
  'paramountplus': 'paramountplus.com',
  'crunchyroll': 'crunchyroll.com',
  'audible': 'audible.com',
  'kindle': 'amazon.com',
  'twitch': 'twitch.tv',
  'xbox': 'xbox.com',
  'playstation': 'playstation.com',
  'psn': 'playstation.com',
  'nintendo': 'nintendo.com',
  'steam': 'steampowered.com',
  'epicgames': 'epicgames.com',
  'siriusxm': 'siriusxm.com',
  'sirius': 'siriusxm.com',

  // Utilities & Services
  'att': 'att.com',
  'at&t': 'att.com',
  'verizon': 'verizon.com',
  'tmobile': 't-mobile.com',
  't-mobile': 't-mobile.com',
  'sprint': 't-mobile.com',
  'comcast': 'xfinity.com',
  'xfinity': 'xfinity.com',
  'spectrum': 'spectrum.com',
  'cox': 'cox.com',
  'centurylink': 'centurylink.com',
  'frontier': 'frontier.com',

  // Rideshare & Delivery
  'uber': 'uber.com',
  'ubereats': 'ubereats.com',
  'lyft': 'lyft.com',
  'doordash': 'doordash.com',
  'grubhub': 'grubhub.com',
  'postmates': 'postmates.com',
  'instacart': 'instacart.com',
  'shipt': 'shipt.com',

  // Travel & Airlines
  'united': 'united.com',
  'unitedairlines': 'united.com',
  'americanairlines': 'aa.com',
  'american airlines': 'aa.com',
  'delta': 'delta.com',
  'deltaairlines': 'delta.com',
  'southwest': 'southwest.com',
  'southwestairlines': 'southwest.com',
  'jetblue': 'jetblue.com',
  'alaska': 'alaskaair.com',
  'alaskaairlines': 'alaskaair.com',
  'spirit': 'spirit.com',
  'spiritairlines': 'spirit.com',
  'frontierairlines': 'flyfrontier.com',
  'flyfrontier': 'flyfrontier.com',
  'allegiant': 'allegiantair.com',
  'hawaiian': 'hawaiianairlines.com',
  'airbnb': 'airbnb.com',
  'vrbo': 'vrbo.com',
  'booking': 'booking.com',
  'expedia': 'expedia.com',
  'hotels': 'hotels.com',
  'kayak': 'kayak.com',
  'priceline': 'priceline.com',
  'marriott': 'marriott.com',
  'hilton': 'hilton.com',
  'hyatt': 'hyatt.com',
  'ihg': 'ihg.com',
  'bestwestern': 'bestwestern.com',
  'choicehotels': 'choicehotels.com',
  'wyndham': 'wyndhamhotels.com',
  'hertz': 'hertz.com',
  'enterprise': 'enterprise.com',
  'avis': 'avis.com',
  'budget': 'budget.com',
  'national': 'nationalcar.com',
  'turo': 'turo.com',

  // Finance & Banking
  'paypal': 'paypal.com',
  'venmo': 'venmo.com',
  'cashapp': 'cash.app',
  'zelle': 'zellepay.com',
  'squarecash': 'cash.app',
  'square': 'squareup.com',
  'stripe': 'stripe.com',
  'chasebank': 'chase.com',
  'chase': 'chase.com',
  'bankofamerica': 'bankofamerica.com',
  'wellsfargo': 'wellsfargo.com',
  'wells fargo': 'wellsfargo.com',
  'citibank': 'citi.com',
  'citi': 'citi.com',
  'capitalone': 'capitalone.com',
  'capital one': 'capitalone.com',
  'usbank': 'usbank.com',
  'pnc': 'pnc.com',
  'td': 'td.com',
  'tdbank': 'td.com',
  'suntrust': 'truist.com',
  'truist': 'truist.com',
  'regions': 'regions.com',
  'ally': 'ally.com',
  'discover': 'discover.com',
  'americanexpress': 'americanexpress.com',
  'amex': 'americanexpress.com',
  'synchrony': 'synchrony.com',

  // Insurance
  'geico': 'geico.com',
  'progressive': 'progressive.com',
  'statefarm': 'statefarm.com',
  'state farm': 'statefarm.com',
  'allstate': 'allstate.com',
  'libertymutual': 'libertymutual.com',
  'liberty mutual': 'libertymutual.com',
  'usaa': 'usaa.com',
  'farmers': 'farmers.com',
  'nationwide': 'nationwide.com',

  // Fitness
  'planetfitness': 'planetfitness.com',
  'planet fitness': 'planetfitness.com',
  'lafitness': 'lafitness.com',
  'la fitness': 'lafitness.com',
  '24hourfitness': '24hourfitness.com',
  '24 hour fitness': '24hourfitness.com',
  'goldsgym': 'goldsgym.com',
  'golds gym': 'goldsgym.com',
  'equinox': 'equinox.com',
  'orangetheory': 'orangetheory.com',
  'crossfit': 'crossfit.com',
  'peloton': 'onepeloton.com',
  'ymca': 'ymca.org',

  // E-commerce
  'ebay': 'ebay.com',
  'etsy': 'etsy.com',
  'wayfair': 'wayfair.com',
  'overstock': 'overstock.com',
  'wish': 'wish.com',
  'aliexpress': 'aliexpress.com',
  'shein': 'shein.com',
  'temu': 'temu.com',
  'zappos': 'zappos.com',
  'asos': 'asos.com',
  'fashionnova': 'fashionnova.com',

  // Subscription Services
  'dropbox': 'dropbox.com',
  'icloud': 'apple.com',
  'googledrive': 'google.com',
  'onedrive': 'microsoft.com',
  'adobe': 'adobe.com',
  'canva': 'canva.com',
  'grammarly': 'grammarly.com',
  'lastpass': 'lastpass.com',
  '1password': '1password.com',
  'dashlane': 'dashlane.com',
  'nordvpn': 'nordvpn.com',
  'expressvpn': 'expressvpn.com',
  'notion': 'notion.so',
  'slack': 'slack.com',
  'zoom': 'zoom.us',

  // Food Delivery Apps
  'seamless': 'seamless.com',
  'caviar': 'trycaviar.com',
  'gopuff': 'gopuff.com',

  // Other Common
  'costcowholesale': 'costco.com',
  'autozone': 'autozone.com',
  'oreillyauto': 'oreillyauto.com',
  'advanceautoparts': 'advanceautoparts.com',
  'jiffy lube': 'jiffylube.com',
  'jiffylube': 'jiffylube.com',
  'firestone': 'firestonecompleteautocare.com',
  'goodyear': 'goodyear.com',
  'discounttire': 'discounttire.com',
  'carmax': 'carmax.com',
  'carvana': 'carvana.com',
}

// Normalize merchant name for lookup
export function normalizeMerchantName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s&-]/g, '') // Remove special chars except & and -
    .replace(/\s+/g, '') // Remove spaces
    .replace(/^(the|a|an)\s*/i, '') // Remove leading articles
    .replace(/#\d+/g, '') // Remove store numbers like #12345
    .replace(/\d{4,}/g, '') // Remove long number sequences
    .trim()
}

// Try to find domain for a merchant
export function getMerchantDomain(merchantName: string | null): string | null {
  if (!merchantName) return null

  const normalized = normalizeMerchantName(merchantName)

  // Direct lookup
  if (MERCHANT_DOMAINS[normalized]) {
    return MERCHANT_DOMAINS[normalized]
  }

  // Try partial matches - check if normalized name starts with or contains a known merchant
  for (const [key, domain] of Object.entries(MERCHANT_DOMAINS)) {
    if (normalized.startsWith(key) || normalized.includes(key)) {
      return domain
    }
  }

  // Try to guess the domain from merchant name
  // Only for single-word or well-formatted names
  const words = merchantName.toLowerCase().replace(/[^a-z\s]/g, '').trim().split(/\s+/)
  if (words.length === 1 && words[0].length >= 3) {
    // Single word, might be a company name - try as domain
    return `${words[0]}.com`
  }

  return null
}

// Get logo URL - uses Google's favicon service which is reliable and free
export function getMerchantLogoUrl(merchantName: string | null, size: number = 80): string | null {
  const domain = getMerchantDomain(merchantName)
  if (!domain) return null

  // Google Favicon API - reliable, no auth needed, supports sizes up to 256
  // The sz parameter gets the best available icon up to that size
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${Math.min(size, 256)}`
}

// Alternative: Google Favicon (works for more sites but lower quality)
export function getMerchantFaviconUrl(merchantName: string | null, size: number = 64): string | null {
  const domain = getMerchantDomain(merchantName)
  if (!domain) return null

  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`
}
